#!/bin/bash
cd $OPENSHIFT_REPO_DIR

export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0_openjdk
export PATH=$JAVA_HOME/bin:$PATH

nohup java -jar app-web/target/app-web-jar-with-dependencies.jar \
--db.url=${OPENSHIFT_MONGODB_DB_HOST}:${OPENSHIFT_MONGODB_DB_PORT} \
--db.name=${OPENSHIFT_APP_NAME} \
--db.username=${OPENSHIFT_MONGODB_DB_USERNAME} \
--db.password=${OPENSHIFT_MONGODB_DB_PASSWORD} \
--server.port=${OPENSHIFT_DIY_PORT} \
--server.address=${OPENSHIFT_DIY_IP} \
> ${OPENSHIFT_DIY_LOG_DIR}/MyHttpServer.log &